name: "Tests"
on:
  push:
    branches:
      - main
      - master
  pull_request:

concurrency:
  group: ci-${{ github.ref }}-tests
  cancel-in-progress: true

jobs:
    build:
      runs-on: ubuntu-latest
      name: Go tests
      steps:
        - uses: actions/checkout@v6
        - name: Setup go
          uses: actions/setup-go@v6
          with:
            go-version-file: 'go.mod'
        - run: go get -v -t -d ./...
        - run: go test -v -race ./...
        - run: go run tests/consumer/consume.go tests/generator/compatibility.dat
